before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
nfpms:
  - id: nfpm-default
    package_name: logknife
    vendor: Nate Sales
    homepage: https://natesales.net/
    maintainer: Nate Sales <nate@natesales.net>
    description: Remove sensitive information from logs
    license: GNU GPL-3.0
    section: utils
    priority: extra
    formats:
      - deb
      - rpm
publishers:
  - name: fury.io
    ids:
      - nfpm-default
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -s -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/natesales/
